plugins {
    id "pl.allegro.tech.build.axion-release" version "1.21.3"
    id "org.sonarqube" version "7.3.1.8318"
}

scmVersion {
    tag.prefix = ""
    useHighestVersion = true
    versionIncrementer("incrementMinorIfNotOnRelease", [releaseBranchPattern: "(?>release|(?>hot)?fix)/.+"])
    branchVersionCreator = [
        "master": "simple",
        "release/.*": "simple",
        ".*": "versionWithBranch"
    ]
}

allprojects {
    version = scmVersion.version
}

sonar {
    properties {
        property "sonar.projectKey", "boolivar_tostring"
        property "sonar.organization", "boolivar"
    }
}