name: CI
on: push
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build
      run: ./gradlew check shadowJar
    - name: Upload test reports
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: '**/build/reports/**/*'
    - name: Release please
      id: release
      if: ${{ github.ref_name == 'master' || startsWith(github.ref_name, 'release/') }}
      uses: googleapis/release-please-action@v4
      with:
        target-branch: ${{ github.ref_name }}
        token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
    - name: Upload Release Artifact
      if: ${{ steps.release.outputs.release_created }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release upload ${{ steps.release.outputs.tag_name }} ./agent/build/libs/agent-${{ steps.release.outputs.version }}.jar#tostring-agent-${{ steps.release.outputs.version }}.jar
